### ISSUE TITLE
QGIS Crash

### ISSUE THREAD

**Issue by subashnalla** [gacarrillor/AppendFeaturesToLayer#20] opened 2023-10-12 07:06 UTC
Hi Team,

QGIS is crashing while using this feature. I have around 35 mif files exported from AutoCAD, trying to append the data in mif files to the respective Geo packages. I have same number of Geo packages created in QGIS, have mapped the source and target layers and exported to JSON format. When I open it and run in batch mode QGIS crashes where as the same functionality is working fine if I run file by file and need help in the same. Please let me know for any other information.

**Comment by gacarrillor** [comment] 2023-10-12 09:14
Hello, thanks for the report.
Could you share some data with us as well as some instructions to attempt to replicate the issue?

**Comment by subashnalla** [comment] 2023-10-13 05:10
Hi Thanks for your reply. Is it possible to have a call so show the issue and discuss.

**Comment by gacarrillor** [comment] 2023-10-13 17:55
That could be possible in the form of consultancy time. If you're interested in that, just let me know your e-mail address and I'll give you my rate per hour.

Otherwise, I invite you to share some data and some step-by-step instructions to replicate the issue.

**Comment by gacarrillor** [comment] 2023-11-29 22:51
Duplicate of #21

**Closed** 2023-11-29 22:51 UTC
Labels: duplicate
